name: Bug report
description: Report a site or data issue
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    id: details
    attributes:
      label: Details
    validations:
      required: true
